name: "CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
        rails:
          - "7.0"
          - "7.1"
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: csv_mapper_test
          POSTGRES_USER: csv_mapper
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      RAILS_VERSION: ${{ matrix.rails }}
      DATABASE_URL: "postgres://csv_mapper:password@localhost:5432/csv_mapper_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Set up database schema
        run: cd spec/dummy; RAILS_ENV=test bundle exec rake db:migrate; cd -
      - name: Run tests
        run: bundle exec rspec
